#!/usr/bin/env bash

source etc/banner
# Banner Add
echo -e "executing: ${LIGHTGREEN}ThePAK${NOCOLOR}"
echo "-----------------------"

unpacking () {
  qemu-i386 $PREFIX/share/quickbms/quickbms -Q -d etc/tools.bms $opt
}

function unpack {
prompt="Please select a file to unpack:"
options=( $(find *.pak) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $opt which is file $REPLY"
         unpacking
        break

    else
        echo "Invalid option. Try another one."
    fi
done
}

function repack {
  echo "Coming soon~"
}

PS3='Please enter your choice: '
options=("Unpack" "Repack" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Unpack")
            unpack
            break
            ;;
        "Repack")
            repack
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done 